---
# defaults file for build-server

public_key: "{{ lookup('file', './keys/ssh-rsa-key.pub') }}"
group_name: {{ group_name }}
datacenter: {{ datacenter }}
server_name: {{ server_name }}
server_count: {{ server_count }}
os_template: {{ os_template }}
storage_type: standard
cpu: {{ cpu-count }}
memory: {{ memory_gb }}
type: standard
disk:
  - sizeGB: {{ disk_size }}
    type: partitioned
    path: {{ disk_mount_point }}
